services:
  milvus:
    image: milvusdb/milvus:v2.5.13
    container_name: milvus_standalone
    ports:
      - "19530:19530" 
      - "9091:9091"   
    volumes:
      - ./milvus_data:/var/lib/milvus
    environment:
      - "ETCD_USE_EMBED=true"
      - "ETCD_DATA_DIR=/var/lib/milvus/etcd"
      - "COMMON_STORAGETYPE=local"